### PR TITLE
delete files specific to code editors

### PR DESCRIPTION
**Pull request by NicolasCARPi**
* remove TwoFactorAuth.phpproj
* remove TwoFactorAuth.sln

They are not used anymore. See https://github.com/RobThree/TwoFactorAuth/pull/119#issuecomment-2057777036

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
This will probably generate a conflict with #119 changes, so I'll fix it once #119 is merged.

**Review by willpower232 — CHANGES_REQUESTED** [review]
should probably remove from the list in composer.json

**Comment by NicolasCARPi** [comment]
@willpower232 done, and I've also merged the new commit from master, which actually deletes the part in composer.json, so I removed them from .gitattributes.

**Review by willpower232 — APPROVED** [review]
lovely job, should I merge this now to free up the next bit?

**Comment by NicolasCARPi** [comment]
Yeah, go crazy with the merge button! I'll probably have a few conflicts to fix afterwards.

**Pull request merged**
