### PR TITLE
Improvements for Composer

### PR DESCRIPTION
**Pull request by lguima**
- Ignored the [vendor folder from Composer](https://getcomposer.org/doc/00-intro.md#dependency-management)
- Replaced the custom autoloader class by the [autoloader from Composer](https://getcomposer.org/doc/01-basic-usage.md#autoloading)

### CODE REVIEW

**Comment by Chofoteddy** [comment]
@RobThree Any updates?

**Comment by RobThree** [comment]
> @RobThree Any updates?

As you can see in #12 I'm not quite sure what to do with this? Or what the actual problem is... If there's a "*the* way" to do this stuff, or even if there's just a "*better* way" to do it then please explain and I'll be glad to implement.

**Comment by lguima** [comment]
@RobThree there's no relation between this PR and the issue #12.

This PR just apply composer autoloader.

**Comment by RobThree** [comment]
> @RobThree there's no relation between this PR and the issue #12.

The relation is that [I have no clue what I'm doing](https://i.imgur.com/o11jgS4.png) with Composer / PSR's etc. As said in #12 I'm primarily a .Net developer and, although I can write a nice piece of PHP code, I'm not familiar (enough) with composer, PSR's etc. so I don't know if this breaks anything, what the impact would be, if people will start complaining etc. (as you can see the continuous integration also breaks on this PR...)

So I _really_ need (decent, substantiated) advice on what to do here, what it actually fixes, what it (potentially) breaks **or** you need to wait until I get around to figuring this stuff out myself and understand the implications and can make a decision on this myself 😉

**Comment by zzanzare** [comment]
I second this PR.

Here is my simple answer to your questions: PSR simply defines a unified way to implement autoloaders, to prevent milions of different implementations doing exactly the same thing - loading a class. And conveniently composer follows that recommendation, so if you are using composer, the only thing to do when autoloading classes is require vendor/autoload.php, which is what people will do when using your library anyway. So it makes sense to do it like that also in the demo and drop the extraneous Loader.

Ignoring vendor directory just prevents the directory from being part of this git repository. Now this is vendor directory of your library, so that would currently only contain Phpunit. It doesn't make sense to commit Phpunit here in your github repo (or keep avoiding commiting it by mistake) since it is already specified in your composer.json and everybody will get it when running composer install.

Disclaimer: I haven't actually executed this PR, I only reviewed the commits, so just make sure it runs.

**Comment by lguima** [comment]
Can someone help me understand what's breaking [Travis CI build](https://travis-ci.org/RobThree/TwoFactorAuth/builds/275908508)?

**Comment by RobThree** [comment]
* The [PHP 5.3 log](https://travis-ci.org/RobThree/TwoFactorAuth/jobs/275908509) says:

    `The command "phpenv global 5.3" failed and exited with 1 during .`

    Which may be something they changed (recently?); after some digging I found [this](https://docs.travis-ci.com/user/reference/trusty#PHP-images):

    > Note: We do not support PHP versions 5.2.x and 5.3.x on Trusty. Specifying it will result in build failure. If you need to test with these versions, use Precise.

    >     matrix:
    >       include:
    >         - php: 5.2
    >           dist: precise
    >         - php: 5.3
    >           dist: precise

* The [PHP7 log](https://travis-ci.org/RobThree/TwoFactorAuth/jobs/275908521) says:

    `Fatal error: Class 'PHPUnit_Framework_TestCase' not found in
    /home/travis/build/RobThree/TwoFactorAuth/tests/TwoFactorAuthTest.php on line 30`

* The [HHVM log](https://travis-ci.org/RobThree/TwoFactorAuth/jobs/275908524) says:

    `This version of PHPUnit is supported on PHP 7.0 and PHP 7.1.
    You are using PHP 5.6.99-hhvm (/usr/bin/hhvm).`

    Which may be a travis-ci problem?

**Comment by RobThree** [comment]
Ok, [this](https://github.com/RobThree/TwoFactorAuth/pull/13#issuecomment-331589741) should all be fixed (albeit quick'n'dirty maybe). I'll look into the rest of this soon so we can merge the pull request or at least fix the problem at hand.

**Pull request closed without merging**
