### PR TITLE
migrate from travis to gh action

### PR DESCRIPTION
**Pull request by MasterOdin**
This PR migrates the test suite from Travis-CI to GitHub actions.

It seems like under GH, testEnsureAllTimeProvidersReturnCorrectTime` becomes much flakier, and so the leniency on this may need to be increased?

### CODE REVIEW

**Comment by willpower232** [comment]
Looks great! I'd be interested to see if PHP 8 tests pass with no changes for kicks.

Did you solve the flakiness with manual re run?

**Comment by MasterOdin** [comment]
Yes

**Review by willpower232 — CHANGES_REQUESTED** [review]
Could you rebase on master so the test updates are included then you can run `composer test` instead of phpunit directly and also `composer lint` (probably not in that order)?

Also have you tried adding PHP 8 to the matrix?

**Comment by willpower232** [comment]
@RobThree do you have any qualms about dropping travis?

**Comment by RobThree** [comment]
> do you have any qualms about dropping travis?

No, not really. As long as we have an alternative, I'm good. Travis has been slow and flakey lately anyway.

**Comment by willpower232** [comment]
:+1: they've massively de-prioritised .org servers to shift everyone to .com so it can take a while to get a test answer!

**Comment by MasterOdin** [comment]
@willpower232 done for both

**Review by willpower232 — APPROVED** [review]

**Comment by willpower232** [comment]
:pray:

**Pull request merged**
