### PR TITLE
Update TwoFactorAuth.php

### PR DESCRIPTION
**Pull request by motsmanish**
Deprecated function: rawurlencode(): Passing null to parameter #1

### CODE REVIEW

**Comment by willpower232** [comment]
Thanks for your attention but aren't those two variables type hinted by the function declaration so can only be strings?

**Comment by RobThree** [comment]
Agree with all above.

**Comment by motsmanish** [comment]
In one of our projects, we use usernames instead of emails. This led to an issue where the library received a null value for the label, causing the error: 'Deprecated function: rawurlencode(): Passing null to parameter'. But no worries, I’ll ensure to include more specific details next time I report an issue.

**Comment by willpower232** [comment]
@motsmanish is it possible you had an older version of the library which didn't have type hinting (see #97)?

**Pull request closed without merging**
